### ISSUE TITLE
not compiling on ubuntu 14.04 with new blitz lib fix

### ISSUE THREAD

**Issue by griffinfoster** [ska-sa/meqtrees-timba#18]
I attempted to compile 74daf5a / v1.3.4 on ubuntu 14.04 (my laptop and elwood), and i get the follow compile error, looks like a blitz issue:

[  4%] Built target timbase
[  6%] Built target viscube
Scanning dependencies of target dmi
[  7%] Built target meqmpi
[ 16%] Built target octopussy
[ 19%] Built target appagent
[ 19%] Building CXX object DMI/CMakeFiles/dmi.dir/src/NumArrayFuncs3.cc.o
[ 22%] Built target apputils
[ 26%] Built target meqserver-lib
Scanning dependencies of target meqnodes
[ 26%] Building CXX object MeqNodes/CMakeFiles/meqnodes.dir/src/TFSmearFactorApprox.cc.o
/home/griffin/meqtrees/meqtrees-timba/MeqNodes/src/TFSmearFactorApprox.cc: In static member function ‘static void Meq::TimeDiff::apply(T1&, T2&, T3, T4, T5, T6, T7, T8, T9, T10, T11)’:
/home/griffin/meqtrees/meqtrees-timba/MeqNodes/src/TFSmearFactorApprox.cc:57:9: error: ‘forward11_stencilop’ is not a member of ‘blitz’
     A = blitz::forward11_stencilop(B,blitz::firstDim);
         ^
/home/griffin/meqtrees/meqtrees-timba/MeqNodes/src/TFSmearFactorApprox.cc: In instantiation of ‘static void Meq::TimeDiff1::apply(T1&, T2&, T3, T4, T5, T6, T7, T8, T9, T10, T11) [with T1 = blitz::FastArrayIterator<double, 2>; T2 = blitz::FastArrayIterator<double, 2>; T3 = blitz::dummy<double>; T4 = blitz::dummy<double>; T5 = blitz::dummy<double>; T6 = blitz::dummy<double>; T7 = blitz::dummy<double>; T8 = blitz::dummy<double>; T9 = blitz::dummy<double>; T10 = blitz::dummy<double>; T11 = blitz::dummy<double>]’:
/usr/include/blitz/array/stencils.cc:382:13:   required from ‘void blitz::applyStencil_imp(const T_stencil&, blitz::Array<T_numtype1, 2>&, T_array2&, T_array3&, T_array4&, T_array5&, T_array6&, T_array7&, T_array8&, T_array9&, T_array10&, T_array11&) [with T_stencil = Meq::TimeDiff1; T_numtype1 = double; T_array2 = blitz::Array<double, 2>; T_array3 = blitz::dummyArray; T_array4 = blitz::dummyArray; T_array5 = blitz::dummyArray; T_array6 = blitz::dummyArray; T_array7 = blitz::dummyArray; T_array8 = blitz::dummyArray; T_array9 = blitz::dummyArray; T_array10 = blitz::dummyArray; T_array11 = blitz::dummyArray]’
/usr/include/blitz/array/stencils.cc:510:46:   required from ‘void blitz::applyStencil(const T_stencil&, blitz::Array<T_numtype1, N_rank>&, T_array2&) [with T_stencil = Meq::TimeDiff1; T_numtype1 = double; int N_rank = 2; T_array2 = blitz::Array<double, 2>]’
/home/griffin/meqtrees/meqtrees-timba/MeqNodes/src/TFSmearFactorApprox.cc:114:58:   required from here
/home/griffin/meqtrees/meqtrees-timba/MeqNodes/src/TFSmearFactorApprox.cc:60:46: error: ‘forward11_stencilop’ was not declared in this scope
     A = forward11_stencilop(B,blitz::firstDim);
                                              ^
...

make[2]: *** [MeqNodes/CMakeFiles/meqnodes.dir/src/TFSmearFactorApprox.cc.o] Error 1
make[1]: *** [MeqNodes/CMakeFiles/meqnodes.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Linking CXX shared library libdmi.so
[ 37%] Built target dmi
make: *** [all] Error 2

**Comment by gijzelaerr** [comment]
what is the blitz version you are using?

probably it is 0.11, which is actually 0.9. You should deinstall that one and make sure 0.10 gets installed.

also make sure you are using the new PPA (radio-astro), and not the old (ska-sa):

https://launchpad.net/~radio-astro/+archive/ubuntu/main

**Comment by griffinfoster** [comment]
I think it would be useful to have it working on the blitz that is on our
main machines (jake/elwood) and what comes with ubuntu as default?

**Comment by gijzelaerr** [comment]
that is 0.10

**Comment by griffinfoster** [comment]
i don't think it works with 0.10 then

**Comment by gijzelaerr** [comment]
just tried a build of 1.3.4 on jake with blitz 0.10, seems to work.

Why don't you use the package?

**Comment by griffinfoster** [comment]
i can confirm v1.3.3 compiles on elwood and my laptop (both with blitz
1.0.10), but i can't get v1.3.4 to compile Which library paths are you
using?

**Comment by gijzelaerr** [comment]
/usr/lib

i'll get access to elwood and investigate what is the problem here. Until then I just suggest to use the packages from the radio-astro PPA.

**Comment by griffinfoster** [comment]
I might be missing something but there is no blitz library on jake in
/usr/lib . When I try bootstrap_cmake on jake I get the following:

Configuring release
executing cmake -DCMAKE_BUILD_TYPE=RELEASE
/home/foster/meqtrees/meqtrees-timba
-- The CXX compiler identification is GNU 4.8.2
-- The C compiler identification is GNU 4.8.2
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
CUDA_TOOLKIT_ROOT_DIR not found or specified
-- Could NOT find CUDA (missing:  CUDA_TOOLKIT_ROOT_DIR
CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) (Required is at
least version "4.0")
 * CUDA not found -- CUDA support disabled. This support is still only
experimental, do not be alarmed.
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Using unsigned short
-- Check if the system is big endian - little endian
-- Looking for include file malloc.h
-- Looking for include file malloc.h - found
-- Looking for include files sys/param.h, sys/mount.h
-- Looking for include files sys/param.h, sys/mount.h - found
-- Looking for include file dlfcn.h
-- Looking for include file dlfcn.h - found
-- Looking for include file stdlib.h
-- Looking for include file stdlib.h - found
-- Looking for include file strings.h
-- Looking for include file strings.h - found
-- Looking for include file string.h
-- Looking for include file string.h - found
-- Looking for include file sys/stat.h
-- Looking for include file sys/stat.h - found
-- Looking for include file unistd.h
-- Looking for include file unistd.h - found
-- Looking for include file memory.h
-- Looking for include file memory.h - found
-- Found PythonInterp: /usr/bin/python (found version "2.7.6")
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so (found
version "2.7.6")
-- INSIDE_VIRTUALENV = False
-- PYTHON_PACKAGES_DIR = /usr/local/lib/python2.7/dist-packages
Found BLITZ include files insame dir
-- Could NOT find BLITZ (missing:  BLITZ_LIBRARY BLITZ_INCLUDE_DIR
BLITZ_INCLUDE_DIR2)
-- A library with BLAS API not found. Please specify library location.
-- LAPACK requires BLAS
-- A library with LAPACK API not found. Please specify library location.
-- Could NOT find CASACORE (missing:  CASACORE_LIBRARIES
CASACORE_INCLUDE_DIR)
CMake Error at
/usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:108
(message):
  Could NOT find DBM (missing: DBM_LIBRARIES DBM_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:315
(_FPHSA_FAILURE_MESSAGE)
  cmake/FindDBM.cmake:33 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  cmake/meqmacros.cmake:86 (FIND_PACKAGE)
  CMakeLists.txt:80 (PACKAGE_DEPENDENCIES)


-- Configuring incomplete, errors occurred!
See also
"/home/foster/meqtrees/meqtrees-timba/build/release/CMakeFiles/CMakeOutput.log".
See also
"/home/foster/meqtrees/meqtrees-timba/build/release/CMakeFiles/CMakeError.log".

**Comment by gijzelaerr** [comment]
ah sorry, I build the packages in a chroot. The development packages for blitz are not installed on jake, since meqtrees is installed there using packages. Why don't you want to use the package?

**Comment by gijzelaerr** [comment]
to wrap up, 0.3.3 should compile with blitz 0.9 (or the 'fake' 0.11 release), 0.3.4 should compile with 0.10. We modified timba in 0.3.4 to compile with the vanilla blitz shipped with ubuntu (0.10). If blitz gives you problems make sure you have the 0.10 package installed on your laptop.

Jake currently has the 0.10 package installed. I can't access elwood at the moment but I think it uses still the old launchpad PPA and thus installs the backported blitz 0.9.

**Comment by gijzelaerr** [comment]
Ok solved. there where 2 problems. on @griffinfoster his laptop the ska-sa PPA blitz (0.11) library was installed. Removed it and installed the new radio-astro launchpad PPA. On jake & elwood the blitz dev package was not installed, so you just could not compile meqtrees-timba.
